<?php

namespace Database\Seeders;

use App\Models\EmployeeTemplate;
use Illuminate\Database\Seeder;

class EmployeeTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $systemTemplates = [
            [
                'name' => 'Sales Representative',
                'description' => 'Standard sales rep with monthly salary and commission',
                'role' => 'sales_rep',
                'employment_type' => 'full_time',
                'position_title' => 'Sales Representative',
                'department' => 'Sales',
                'pay_type' => 'salary',
                'pay_amount' => 150000.00,
                'pay_frequency' => 'monthly',
                'standard_hours_per_week' => 40,
                'commission_rate' => 5.00,
                'commission_cap' => null,
                'tax_handling' => 'shop_calculates',
                'pension_enabled' => true,
                'pension_employee_rate' => 8.00,
                'nhf_enabled' => false,
                'nhis_enabled' => true,
            ],
            [
                'name' => 'Cashier',
                'description' => 'Standard cashier with hourly pay',
                'role' => 'cashier',
                'employment_type' => 'full_time',
                'position_title' => 'Cashier',
                'department' => 'Sales',
                'pay_type' => 'hourly',
                'pay_amount' => 800.00,
                'pay_frequency' => 'weekly',
                'standard_hours_per_week' => 40,
                'commission_rate' => null,
                'commission_cap' => null,
                'tax_handling' => 'shop_calculates',
                'pension_enabled' => true,
                'pension_employee_rate' => 8.00,
                'nhf_enabled' => false,
                'nhis_enabled' => true,
            ],
            [
                'name' => 'Store Manager',
                'description' => 'Senior store manager with full benefits',
                'role' => 'store_manager',
                'employment_type' => 'full_time',
                'position_title' => 'Store Manager',
                'department' => 'Management',
                'pay_type' => 'salary',
                'pay_amount' => 350000.00,
                'pay_frequency' => 'monthly',
                'standard_hours_per_week' => 45,
                'commission_rate' => 2.00,
                'commission_cap' => 100000.00,
                'tax_handling' => 'shop_calculates',
                'pension_enabled' => true,
                'pension_employee_rate' => 8.00,
                'nhf_enabled' => true,
                'nhis_enabled' => true,
            ],
            [
                'name' => 'Inventory Clerk',
                'description' => 'Inventory management staff',
                'role' => 'inventory_clerk',
                'employment_type' => 'full_time',
                'position_title' => 'Inventory Clerk',
                'department' => 'Inventory',
                'pay_type' => 'salary',
                'pay_amount' => 120000.00,
                'pay_frequency' => 'monthly',
                'standard_hours_per_week' => 40,
                'commission_rate' => null,
                'commission_cap' => null,
                'tax_handling' => 'shop_calculates',
                'pension_enabled' => true,
                'pension_employee_rate' => 8.00,
                'nhf_enabled' => false,
                'nhis_enabled' => true,
            ],
            [
                'name' => 'Part-Time Associate',
                'description' => 'Part-time retail associate with hourly pay',
                'role' => 'sales_rep',
                'employment_type' => 'part_time',
                'position_title' => 'Retail Associate',
                'department' => 'Sales',
                'pay_type' => 'hourly',
                'pay_amount' => 600.00,
                'pay_frequency' => 'weekly',
                'standard_hours_per_week' => 20,
                'commission_rate' => null,
                'commission_cap' => null,
                'tax_handling' => 'shop_calculates',
                'pension_enabled' => false,
                'pension_employee_rate' => 8.00,
                'nhf_enabled' => false,
                'nhis_enabled' => false,
            ],
            [
                'name' => 'Seasonal Worker',
                'description' => 'Temporary seasonal employee with daily pay',
                'role' => 'sales_rep',
                'employment_type' => 'seasonal',
                'position_title' => 'Seasonal Staff',
                'department' => 'Sales',
                'pay_type' => 'daily',
                'pay_amount' => 5000.00,
                'pay_frequency' => 'weekly',
                'standard_hours_per_week' => 40,
                'commission_rate' => null,
                'commission_cap' => null,
                'tax_handling' => 'employee_calculates',
                'pension_enabled' => false,
                'pension_employee_rate' => 8.00,
                'nhf_enabled' => false,
                'nhis_enabled' => false,
            ],
            [
                'name' => 'Commission Sales Agent',
                'description' => 'Commission-only sales agent',
                'role' => 'sales_rep',
                'employment_type' => 'contract',
                'position_title' => 'Sales Agent',
                'department' => 'Sales',
                'pay_type' => 'commission_based',
                'pay_amount' => 0.00,
                'pay_frequency' => 'monthly',
                'standard_hours_per_week' => 40,
                'commission_rate' => 15.00,
                'commission_cap' => null,
                'tax_handling' => 'employee_calculates',
                'pension_enabled' => false,
                'pension_employee_rate' => 8.00,
                'nhf_enabled' => false,
                'nhis_enabled' => false,
            ],
            [
                'name' => 'Intern',
                'description' => 'Training intern with stipend',
                'role' => 'sales_rep',
                'employment_type' => 'intern',
                'position_title' => 'Intern',
                'department' => 'Operations',
                'pay_type' => 'salary',
                'pay_amount' => 50000.00,
                'pay_frequency' => 'monthly',
                'standard_hours_per_week' => 30,
                'commission_rate' => null,
                'commission_cap' => null,
                'tax_handling' => 'exempt',
                'pension_enabled' => false,
                'pension_employee_rate' => 8.00,
                'nhf_enabled' => false,
                'nhis_enabled' => false,
            ],
        ];

        foreach ($systemTemplates as $templateData) {
            EmployeeTemplate::updateOrCreate(
                [
                    'is_system' => true,
                    'tenant_id' => null,
                    'name' => $templateData['name'],
                ],
                array_merge($templateData, [
                    'is_system' => true,
                    'tenant_id' => null,
                ])
            );
        }

        $this->command->info('Created '.count($systemTemplates).' system employee templates');
    }
}
