import type { ResolvedTheme, TemplateData } from '../types/storefront';

export const classicCommerceTemplate: TemplateData = {
    slug: 'classic-commerce',
    animation_tier: 'subtle',
    structural_config: {
        container_max_width: '1280px',
    },
};

interface ThemeSpec {
    name: string;
    colors: Record<string, string>;
    colorsDark?: Record<string, string>;
    headingFont: string;
    bodyFont: string;
    headingWeight?: string;
    bodyWeight?: string;
    borderRadius?: string;
    sectionSpacing?: string;
    shadowDepth?: string;
    buttonRadius?: string;
    cardBorder?: string;
    headingTransform?: string;
    imageRadius?: string;
    dividerStyle?: string;
    headerVariant?: string;
    footerVariant?: string;
    heroVariant?: string;
    cardVariant?: string;
    categoryVariant?: string;
    testimonialsVariant?: string;
    newsletterVariant?: string;
    imageTextVariant?: string;
    contactVariant?: string;
    featuredVariant?: string;
}

function makeTheme(spec: ThemeSpec): ResolvedTheme & { name: string; colorsDark: Record<string, string>; sectionDefaults: Record<string, string> } {
    const lightColors = {
        primary: '#e94560',
        'primary-foreground': '#ffffff',
        secondary: '#064E3B',
        accent: '#f59e0b',
        'accent-foreground': '#ffffff',
        background: '#ffffff',
        foreground: '#111827',
        'card-bg': '#ffffff',
        surface: '#f5f5f5',
        border: '#e5e7eb',
        text: '#374151',
        'text-muted': '#6b7280',
        'muted-foreground': '#6b7280',
        'footer-bg': '#111111',
        'footer-text': '#ffffff',
        success: '#22c55e',
        error: '#dc2626',
        ...spec.colors,
    };

    const darkDefaults: Record<string, string> = {
        primary: lightColors.primary,
        'primary-foreground': '#ffffff',
        secondary: lightColors.secondary,
        accent: lightColors.accent,
        'accent-foreground': '#ffffff',
        background: '#0f1117',
        foreground: '#f0f0f2',
        'card-bg': '#1a1c25',
        surface: '#14161e',
        border: '#2a2d38',
        text: '#c8cad0',
        'text-muted': '#7a7e8a',
        'muted-foreground': '#7a7e8a',
        'footer-bg': '#090a0e',
        'footer-text': '#c8cad0',
        success: '#34d399',
        error: '#f87171',
    };

    return {
        name: spec.name,
        colors: lightColors,
        colorsDark: { ...darkDefaults, ...spec.colorsDark },
        typography: {
            heading_font: spec.headingFont,
            body_font: spec.bodyFont,
            heading_weight: spec.headingWeight ?? '700',
            body_weight: spec.bodyWeight ?? '400',
            base_size: 16,
            line_height: 1.5,
        },
        components: {
            button_style: 'solid',
            input_style: 'bordered',
            card_style: 'elevated',
            button_radius: spec.buttonRadius ?? 'rounded',
            card_border: spec.cardBorder ?? 'subtle',
            heading_transform: spec.headingTransform ?? 'normal',
        },
        feel: {
            border_radius: spec.borderRadius ?? '8px',
            section_spacing: spec.sectionSpacing ?? '64px',
            shadow_depth: spec.shadowDepth ?? '0 1px 3px rgba(0,0,0,0.1)',
            image_radius: spec.imageRadius ?? 'soft',
            divider_style: spec.dividerStyle ?? 'none',
        },
        animation: {
            entrance_style: 'fade-up',
            hover_style: 'lift',
        },
        header: {
            variant: spec.headerVariant ?? 'standard',
            position: 'sticky',
        },
        footer: {
            variant: spec.footerVariant ?? 'multi_column',
        },
        hero: {
            default_variant: spec.heroVariant ?? 'centered_overlay',
        },
        product_card: {
            variant: spec.cardVariant ?? 'default',
        },
        decorations: {},
        sectionDefaults: {
            hero_banner: spec.heroVariant ?? 'centered_overlay',
            featured_products: spec.featuredVariant ?? 'standard_grid',
            category_grid: spec.categoryVariant ?? 'image_above',
            testimonials: spec.testimonialsVariant ?? 'grid',
            newsletter_signup: spec.newsletterVariant ?? 'inline',
            image_with_text: spec.imageTextVariant ?? 'side_by_side',
            contact_form: spec.contactVariant ?? 'stacked',
        },
    };
}

export const classicCommerceThemes = [
    makeTheme({
        name: 'Lagos Express',
        colors: {
            primary: '#e94560',
            'primary-foreground': '#ffffff',
            secondary: '#1a1a2e',
            accent: '#f59e0b',
            background: '#ffffff',
            foreground: '#111827',
            surface: '#f8f9fb',
            border: '#e5e7eb',
            text: '#374151',
            'text-muted': '#6b7280',
            'footer-bg': '#111111',
        },
        colorsDark: {
            primary: '#ff6b81',
            accent: '#fbbf24',
            background: '#0c0c14',
            foreground: '#f5f5f7',
            'card-bg': '#161621',
            surface: '#111119',
            border: '#2a2a3a',
            text: '#d1d1d9',
            'text-muted': '#8888a0',
            'muted-foreground': '#8888a0',
            'footer-bg': '#060609',
            'footer-text': '#d1d1d9',
        },
        headingFont: 'DM Sans',
        bodyFont: 'DM Sans',
        headingWeight: '700',
        borderRadius: '8px',
        sectionSpacing: '64px',
        shadowDepth: '0 2px 8px rgba(0,0,0,0.08)',
        buttonRadius: 'rounded',
        cardBorder: 'subtle',
        headingTransform: 'normal',
        imageRadius: 'soft',
        dividerStyle: 'none',
        heroVariant: 'centered_overlay',
        featuredVariant: 'standard_grid',
        categoryVariant: 'image_above',
        testimonialsVariant: 'grid',
        newsletterVariant: 'inline',
        cardVariant: 'default',
    }),

    makeTheme({
        name: 'Sunshine Market',
        colors: {
            primary: '#f97316',
            'primary-foreground': '#ffffff',
            secondary: '#92400e',
            accent: '#dc2626',
            background: '#fffbf0',
            foreground: '#1a1a1a',
            'card-bg': '#ffffff',
            surface: '#fff7ed',
            border: '#fed7aa',
            text: '#451a03',
            'text-muted': '#9a3412',
            'muted-foreground': '#9a3412',
            'footer-bg': '#1c1917',
            'footer-text': '#fef3c7',
        },
        colorsDark: {
            primary: '#fb923c',
            accent: '#ef4444',
            background: '#141110',
            foreground: '#fef3c7',
            'card-bg': '#1f1b17',
            surface: '#1a1611',
            border: '#3d3428',
            text: '#e8d5b8',
            'text-muted': '#a08968',
            'muted-foreground': '#a08968',
            'footer-bg': '#0a0908',
            'footer-text': '#e8d5b8',
        },
        headingFont: 'Poppins',
        bodyFont: 'Poppins',
        headingWeight: '600',
        borderRadius: '12px',
        sectionSpacing: '56px',
        shadowDepth: '0 4px 14px rgba(0,0,0,0.06)',
        buttonRadius: 'pill',
        cardBorder: 'none',
        headingTransform: 'normal',
        imageRadius: 'rounded',
        dividerStyle: 'none',
        heroVariant: 'slideshow',
        featuredVariant: 'carousel',
        categoryVariant: 'chips',
        testimonialsVariant: 'carousel',
        newsletterVariant: 'stacked',
        imageTextVariant: 'stacked',
        cardVariant: 'default',
    }),

    makeTheme({
        name: 'Abuja Fresh',
        colors: {
            primary: '#16a34a',
            'primary-foreground': '#ffffff',
            secondary: '#064E3B',
            accent: '#059669',
            background: '#ffffff',
            foreground: '#111827',
            surface: '#f0fdf4',
            border: '#d1fae5',
            text: '#374151',
            'text-muted': '#6b7280',
            'footer-bg': '#052e16',
            'footer-text': '#ecfdf5',
        },
        colorsDark: {
            primary: '#22c55e',
            accent: '#10b981',
            background: '#0a120e',
            foreground: '#ecfdf5',
            'card-bg': '#0f1f17',
            surface: '#0c1a12',
            border: '#1a3a28',
            text: '#b8e0cc',
            'text-muted': '#6da888',
            'muted-foreground': '#6da888',
            'footer-bg': '#060e09',
            'footer-text': '#b8e0cc',
        },
        headingFont: 'DM Sans',
        bodyFont: 'DM Sans',
        headingWeight: '600',
        borderRadius: '8px',
        sectionSpacing: '72px',
        shadowDepth: '0 1px 3px rgba(0,0,0,0.06)',
        buttonRadius: 'rounded',
        cardBorder: 'visible',
        headingTransform: 'uppercase',
        imageRadius: 'sharp',
        dividerStyle: 'line',
        heroVariant: 'split_image',
        featuredVariant: 'spotlight_plus_grid',
        categoryVariant: 'icon_grid',
        testimonialsVariant: 'single_spotlight',
        newsletterVariant: 'inline',
        imageTextVariant: 'overlap',
        contactVariant: 'side_by_side',
        cardVariant: 'minimal',
        footerVariant: 'centered',
    }),

    makeTheme({
        name: 'Crystal Clear',
        colors: {
            primary: '#0ea5e9',
            'primary-foreground': '#ffffff',
            secondary: '#475569',
            accent: '#0284c7',
            background: '#ffffff',
            foreground: '#0f172a',
            surface: '#f8fafc',
            border: '#e2e8f0',
            text: '#475569',
            'text-muted': '#94a3b8',
            'muted-foreground': '#94a3b8',
            'footer-bg': '#0f172a',
            'footer-text': '#e2e8f0',
        },
        colorsDark: {
            primary: '#38bdf8',
            accent: '#0ea5e9',
            background: '#0b1120',
            foreground: '#e2e8f0',
            'card-bg': '#111a2e',
            surface: '#0e1526',
            border: '#1e293b',
            text: '#b0bfd0',
            'text-muted': '#64748b',
            'muted-foreground': '#64748b',
            'footer-bg': '#060c18',
            'footer-text': '#94a3b8',
        },
        headingFont: 'Inter',
        bodyFont: 'Inter',
        headingWeight: '500',
        borderRadius: '6px',
        sectionSpacing: '80px',
        shadowDepth: '0 1px 2px rgba(0,0,0,0.04)',
        buttonRadius: 'sharp',
        cardBorder: 'subtle',
        headingTransform: 'uppercase',
        imageRadius: 'sharp',
        dividerStyle: 'line',
        heroVariant: 'minimal_text',
        featuredVariant: 'horizontal_scroll',
        categoryVariant: 'image_overlay',
        testimonialsVariant: 'single_spotlight',
        newsletterVariant: 'stacked',
        imageTextVariant: 'side_by_side',
        cardVariant: 'default',
        headerVariant: 'centered_logo',
        footerVariant: 'minimal',
    }),

    makeTheme({
        name: 'Naija Vibrant',
        colors: {
            primary: '#0d9488',
            'primary-foreground': '#ffffff',
            secondary: '#f43f5e',
            accent: '#f43f5e',
            background: '#ffffff',
            foreground: '#111827',
            surface: '#f0fdfa',
            border: '#ccfbf1',
            text: '#374151',
            'text-muted': '#6b7280',
            'footer-bg': '#0f172a',
            'footer-text': '#f0fdfa',
        },
        colorsDark: {
            primary: '#14b8a6',
            secondary: '#fb7185',
            accent: '#fb7185',
            background: '#0a1210',
            foreground: '#f0fdfa',
            'card-bg': '#0f1e1a',
            surface: '#0c1915',
            border: '#1a3830',
            text: '#b0d8cc',
            'text-muted': '#6aaa96',
            'muted-foreground': '#6aaa96',
            'footer-bg': '#060e0b',
            'footer-text': '#b0d8cc',
        },
        headingFont: 'Outfit',
        bodyFont: 'Outfit',
        headingWeight: '700',
        borderRadius: '10px',
        sectionSpacing: '60px',
        shadowDepth: '0 4px 12px rgba(0,0,0,0.08)',
        buttonRadius: 'pill',
        cardBorder: 'none',
        headingTransform: 'normal',
        imageRadius: 'rounded',
        dividerStyle: 'none',
        heroVariant: 'asymmetric',
        featuredVariant: 'masonry',
        categoryVariant: 'carousel',
        testimonialsVariant: 'grid',
        newsletterVariant: 'inline',
        imageTextVariant: 'overlap',
        cardVariant: 'overlay',
        footerVariant: 'multi_column',
    }),

    makeTheme({
        name: 'Metro Professional',
        colors: {
            primary: '#1e3a5f',
            'primary-foreground': '#ffffff',
            secondary: '#475569',
            accent: '#0369a1',
            background: '#f8fafc',
            foreground: '#0f172a',
            'card-bg': '#ffffff',
            surface: '#f1f5f9',
            border: '#cbd5e1',
            text: '#475569',
            'text-muted': '#94a3b8',
            'muted-foreground': '#94a3b8',
            'footer-bg': '#0f172a',
            'footer-text': '#cbd5e1',
        },
        colorsDark: {
            primary: '#3b82f6',
            accent: '#0ea5e9',
            background: '#0c1017',
            foreground: '#e2e8f0',
            'card-bg': '#121824',
            surface: '#0f141e',
            border: '#1e293b',
            text: '#94a3b8',
            'text-muted': '#64748b',
            'muted-foreground': '#64748b',
            'footer-bg': '#070a10',
            'footer-text': '#94a3b8',
        },
        headingFont: 'DM Sans',
        bodyFont: 'DM Sans',
        headingWeight: '600',
        borderRadius: '6px',
        sectionSpacing: '72px',
        shadowDepth: '0 1px 2px rgba(0,0,0,0.04)',
        buttonRadius: 'sharp',
        cardBorder: 'visible',
        headingTransform: 'uppercase',
        imageRadius: 'sharp',
        dividerStyle: 'line',
        heroVariant: 'centered_overlay',
        featuredVariant: 'standard_grid',
        categoryVariant: 'image_above',
        testimonialsVariant: 'carousel',
        newsletterVariant: 'stacked',
        imageTextVariant: 'side_by_side',
        contactVariant: 'side_by_side',
        cardVariant: 'detailed',
        footerVariant: 'minimal',
    }),
];

export type CatalogTheme = (typeof classicCommerceThemes)[number];
